default_install_hook_types: [ pre-commit, commit-msg ]

repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black-jupyter
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.12
        stages: [ pre-commit ]
  #        args: [ --line-length=88, --preview, --unstable ]

  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: "v4.1.0"
    hooks:
      - id: commitizen
        stages: [ commit-msg ]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.8.3"
    hooks:
      - id: ruff
        types_or: [ python, pyi ]
        stages: [ pre-commit ]

  # waiting for https://github.com/gee-community/geetools/issues/337
  # so notebooks can again be executed from the documentation
  - repo: "https://github.com/kynan/nbstripout"
    rev: "0.8.1"
    hooks:
      - id: nbstripout
        stages: [ pre-commit ]